services:
  server:
    build: .
    ports:
      - 8000:8000
    volumes:
      - static:/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: vinat
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d vinat"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/app/static
    depends_on:
      - server
volumes:
  db:
  static:
