# Generated by Django 2.2.2 on 2019-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190917_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='passport',
            field=models.FileField(upload_to='passports'),
        ),
    ]
